# Generated by Django 5.2 on 2025-04-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('esforco', models.CharField(choices=[('b', 'baixo'), ('m', 'medio'), ('a', 'alto')], max_length=2, verbose_name='Esforço para o habito')),
            ],
        ),
        migrations.CreateModel(
            name='Heroi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('xp', models.FloatField(default=0)),
                ('forca', models.FloatField(default=0)),
                ('inteligencia', models.FloatField(default=0)),
                ('carisma', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('frequencia', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitos.area')),
                ('heroi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitos.heroi')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='heroi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitos.heroi'),
        ),
        migrations.CreateModel(
            name='HistoricoHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('completo', models.BooleanField()),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitos.habito')),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda', models.BooleanField()),
                ('terça', models.BooleanField()),
                ('quarta', models.BooleanField()),
                ('quinta', models.BooleanField()),
                ('sexta', models.BooleanField()),
                ('sabado', models.BooleanField()),
                ('domingo', models.BooleanField()),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitos.habito')),
            ],
        ),
    ]
