# Generated by Django 5.2 on 2025-04-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habito',
            name='frequencia',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='heroi',
            name='carisma',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='heroi',
            name='forca',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='heroi',
            name='inteligencia',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='heroi',
            name='xp',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='semana',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semana',
            name='quarta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semana',
            name='quinta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semana',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semana',
            name='segunda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semana',
            name='sexta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semana',
            name='terça',
            field=models.BooleanField(default=False),
        ),
    ]
